config/routes.rb
Rails.application.routes.draw do

  
  resources :members
  resources :teams
  root to: "teams#index"

  resource :session

  get '/login' => "sessions#new", as: :login
  get '/logout' => "sessions#destroy", as: :logout
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
    belongs_to :team
    has_and_belongs_to_many :positions
    #has_one :position
    validates :firstname, :lastname, :number, :birthday, presence: true
end

app/models/position.rb
class Position < ApplicationRecord
    #belongs_to :member
    has_and_belongs_to_many :members
end

app/models/team.rb
class Team < ApplicationRecord
    has_many :members
    validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    def self.authenticate(email, password)
        user = find_by_email(email)
        return user if user && user.authenticate(password)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protected
    
    def current_user
        @current_user ||= session[:user_id] && User.find_by(id: session[:user_id])
    end
    helper_method :current_user

    def logged_in?
        current_user.is_a? User
    end
    helper_method :logged_in?

    def access_denied
        redirect_to login_path, notice: "please login to continue" and return false
    end

    def authenticate
        logged_in? ? true : access_denied
    end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: %i[ show edit update destroy ]
  # before_action :authenticate, except: [:index, :show]

  http_basic_authenticate_with :name => "user", :password => "secret", :except => [:index, :show]
 
  # GET /members or /members.json
  def index
    @members = Member.all
  end

  # GET /members/1 or /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members or /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: "Member was successfully created." }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1 or /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: "Member was successfully updated." }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1 or /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: "Member was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def member_params
      params.require(:member).permit(:firstname, :lastname, :number, :birthday, :team_id, {position_ids: []})
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    
    def create
        if user = User.authenticate(params[:email], params[:password])
        session[:user_id] = user.id
        redirect_to root_path, notice: "Logged in successfully"
        else
        render action: 'new'
        end
    end

    def destroy
        reset_session
        redirect_to root_path, notice: "logged out successfully"
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: %i[ show edit update destroy ]
  # before_action :authenticate, except: [:index, :show]

  http_basic_authenticate_with :name => "user", :password => "secret", :only => :destroy
  # GET /teams or /teams.json
  def index
    @teams = Team.all
  end

  # GET /teams/1 or /teams/1.json
  def show
  end

  # GET /teams/new
  def new
    @team = Team.new
  end

  # GET /teams/1/edit
  def edit
  end

  # POST /teams or /teams.json
  def create
    @team = Team.new(team_params)

    respond_to do |format|
      if @team.save
        format.html { redirect_to @team, notice: "Team was successfully created." }
        format.json { render :show, status: :created, location: @team }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teams/1 or /teams/1.json
  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to @team, notice: "Team was successfully updated." }
        format.json { render :show, status: :ok, location: @team }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1 or /teams/1.json
  def destroy
    @team.destroy
    respond_to do |format|
      format.html { redirect_to teams_url, notice: "Team was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def team_params
      params.require(:team).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
      <title>TeamsManager</title>
      <meta name="viewport" content="width=device-width,initial-scale=1">
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.2/css/bulma.min.css">
      <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>



<body>

  <%= render "shared/header" %>

  <% if notice.present? %>
  <div class="notification is-link is-light"><%= notice %></div>
  <% end %>

  <% if alert.present? %>
  <div class="notification is-danger is-light"><%= alert %></div>
  <% end %>

  <% if logged_in? %>
      <%= current_user.email %>
      <%= link_to 'Logout', logout_path %>
  <% else %>
      <div class="notification is-info is-light">
          <%= link_to 'Login', login_path %> 
        </div>
   <% end %>

  <div class="container">
    <%= yield %>
  </div>
</body>

</html>

app/views/members/_form.html.erb
<%= form_with(model: member) do |form| %>
  <% if member.errors.any? %>
    <div class="message is-danger">
        <div class="message-header">
           <p><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</p>
        </div>

     <div class="message-body">
        <ul>
          <% member.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :firstname, class: "label" %>
    <%= form.text_field :firstname, class: "input" %>
  </div>

  <div class="field">
    <%= form.label :lastname, class: "label" %>
    <%= form.text_field :lastname, class: "input" %>
  </div>

  <div class="field">
    <%= form.label :number, class: "label" %>
    <%= form.number_field :number, class: "input" %>
  </div>

  <div class="field">
    <%= form.label :birthday, class: "label" %>
    <%= form.text_field :birthday, class: "input" %>
  </div>

  <div class="field">
    <%= form.label :team_id, class: "label" %>
    <div class="select">
    <%= form.select :team_id, Team.all.collect {|u| [u.name, u.id]} %>
    </div>
  </div>

  <div class="field">
    <%= form.label "Positions", class: "label"%>
     <div class="select">
       <%= form.select "position_id", Position.all.collect {|u| [u.name, u.id]} %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit class: "button is-success" %>
  </div>
<% end %>

app/views/members/edit.html.erb
<div class="columns is-centered mt-6">
    <div class="column is-one-third">
        <h1 class="is-size-2 has-text-weight-bold mb-3">Editing Member</h1>
        <%= render 'form' , member: @member %>
    </div>
</div>

app/views/members/index.html.erb
<% content_for :title do %>
  Members  &ndash; <%= DateTime.now.to_s(:_date) %>
<% end %>

<div class="columns mt-6 is-centered">
       <% @members.each do |member| %>
          <div class="column is-one-quarter">
               <div class="card">
                  <header class="card-header">
                    <p class="card-header-title"><%= member.team.name %></p>
                 </header>

                  <div class="card-content"> 
                      <div class="content">
                        <p>firstname:<span class="has-text-weight-bold"><%= member.firstname %></span></p>                    
                        <p>lastname:<span class="has-text-weight-bold"><%= member.lastname %></span> </p>
                        <p>number:<span class="has-text-weight-bold"><%= member.number %></span> </p>
                        <p>birthday:<span class="has-text-weight-bold"><%= member.birthday %></span></p> 
                        <p class="italic">Logged <%= time_ago_in_words(member.created_at) %> ago</p>            
                      </div>
                  </div>

                  <div class="card-footer">
                      <%= link_to 'Show', member, class: "card-footer-item" %>
                      <%= link_to 'Edit', edit_member_path(member), class: "card-footer-item" %>
                      <%= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' }, class: "card-footer-item" %>
                  </div>
               </div>
          </div>
       <% end %>
</div>

app/views/members/new.html.erb
<div class="columns is-centered mt-6">
    <div class="column is-one-third">
        <h1 class="is-size-2 has-text-weight-bold mb-3">New Member</h1>
        <%= render 'form' , member: @member %>
    </div>
</div>

app/views/members/show.html.erb
<% content_for :title do %>
  Hello &ndash; <%= @member.firstname %>  
<% end %>

<div class="columns mt-6 is-centered">
    <div class="column is-one-third"> 
        <nav class="panel is-link"> 
          <p class="panel-heading">
          <%= @member.firstname %> - Team
           <%= @member.team.name%>
          </p>

          <div class="panel-block">
           Firstname:<%= @member.firstname %>
          </div>

          <div class="panel-block">
           Lastname:<%= @member.lastname %>
          </div>

           <div class="panel-block">
           Number:<%= @member.number %>
          </div>

          <div class="panel-block">
           Birthday:<%= @member.birthday %>
          </div>

        <div class="panel-block">
           Team:<%= @member.team.name %>
        </div>

        </nav>

          <div class="columns is-mobile">
              <div class="column">
               <%= link_to 'Edit', edit_member_path(@member), class: "button is-gray"  %> 
                <%= link_to 'Back', members_path, class: "button is-gray" %>
              </div>
          </div>
    </div>
</div>

app/views/shared/_header.html.erb
<section class="hero is-link is-small">
    <!-- Hero head: will stick at the top -->
    <div class="hero-head">
        <nav class="navbar">
            <div class="container">
                <div class="navbar-brand">
                    <%= link_to root_path, class: "navbar-item" do %>
                    <svg width="30" height="30" viewBox="0 0 30 30" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path opacity="0.4" d="M22.3596 13.6209C24.1034 13.3759 25.4459 11.8809 25.4496 10.0696C25.4496 8.28463 24.1484 6.80463 22.4421 6.52463" stroke="white" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                    <path d="M24.6606 17.8129C26.3494 18.0654 27.5281 18.6566 27.5281 19.8754C27.5281 20.7141 26.9731 21.2591 26.0756 21.6016" stroke="white" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                    <path fill-rule="evenodd" clip-rule="evenodd" d="M14.8584 18.3297C10.8409 18.3297 7.40967 18.9385 7.40967 21.3697C7.40967 23.7997 10.8197 24.426 14.8584 24.426C18.8759 24.426 22.3059 23.8235 22.3059 21.391C22.3059 18.9585 18.8972 18.3297 14.8584 18.3297Z" stroke="white" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                    <path opacity="0.4" fill-rule="evenodd" clip-rule="evenodd" d="M14.8585 14.8599C17.4948 14.8599 19.6323 12.7236 19.6323 10.0861C19.6323 7.44988 17.4948 5.31238 14.8585 5.31238C12.2223 5.31238 10.0848 7.44988 10.0848 10.0861C10.0748 12.7136 12.196 14.8511 14.8235 14.8599H14.8585Z" stroke="white" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                    <path opacity="0.4" d="M7.35611 13.6209C5.61111 13.3759 4.26986 11.8809 4.26611 10.0696C4.26611 8.28463 5.56736 6.80463 7.27361 6.52463" stroke="white" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                    <path d="M5.055 17.8129C3.36625 18.0654 2.1875 18.6566 2.1875 19.8754C2.1875 20.7141 2.7425 21.2591 3.64 21.6016" stroke="white" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                    </svg>
                    <span class="has-text-weight-bold is-size-4 ml-4">Teamly</span>
                    <% end %>
                    <span class="navbar-burger" data-target="navbarMenuHeroA">
                        <span></span>
                        <span></span>
                        <span></span>
                    </span>
                </div>
                <div id="navbarMenuHeroA" class="navbar-menu">
                    <div class="navbar-end">
                        <span class="navbar-item">
                            <%= link_to "Create new team" , new_team_path, class:"button is-success"%>
                        </span>
                        <span class="navbar-item">
                            <%= link_to "Create new member" , new_member_path, class:"button is-outlined"%>
                        </span>
                    </div>
                </div>
            </div>
        </nav>
    </div>

    <!-- Hero content: will be in the middle -->
    <div class="hero-body">
        <div class="container has-text-centered">
            <p class="title">
                <% if content_for(:title)%>
                    <%= yield :title %>
                        <% else %>
                            Teams
                            <% end %>
            </p>
        </div>
    </div>
</section>